import DatePicker from '@/components/atom/DatePicker'
import { Geist, Geist_Mono } from 'next/font/google'
import Head from 'next/head'
import { useState } from 'react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function Home() {
  const [selectedDate, setSelectedDate] = useState<Date | null>(null)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DatePicker
        value={selectedDate}
        onChange={(date: Date | undefined) => {
          setSelectedDate(date ?? null)
        }}
        disabled={false}
      />
    </>
  )
}
